### ISSUE TITLE
Verify bot?

### ISSUE THREAD

**Issue by diziara** [WaltWh/LongSphinx#81]
How does one achieve verified status for the bot? Is it possible for Tim/Cecil to be verified?

**Comment by diziara** [comment]
I haven't read it yet, but this seems related: https://support.discordapp.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by WaltWh** [comment]
Looks like verification is still only available if you're in more than 75 servers, which seems unlikely to happen. On the plus side, this does mean that with the current policies, we don't need verification to retain all of our privileges. Closing this; will re-open if Discord changes their policies in a way that affects us.
